---
project: pset-devops
kind: PIPELINE
name: vmw-veba-deploy
icon: organization,left, is-ultramarine
enabled: true
description: Pipeline to deploy VEBA using the VEBA blueprint
concurrency: 10
workspace:
  endpoint: ''
  image: ''
  registry: ''
  path: ''
  autoCloneForTrigger: false
  limits:
    cpu: 1.0
    memory: 512
stageOrder:
- Stage0
stages:
  Stage0:
    taskOrder:
    - Task0
    tasks:
      Task0:
        type: Blueprint
        endpoints:
          gitServer: cloud-automation-content
        input:
          action: CreateDeployment
          blueprint: ''
          deploymentName: ''
          parameters:
            vcenterPassword: VMware1!
            vebaHostname: veba01
            vebaRootPassword: VMware1!
            vcenterUsername: administrator@vsphere.local
            vcenterServer: vc01.domain.local
            openFaasPassword: VMware1!
            vcenterDisableTLSVerification: 'True'
            deploymentImage: http://minio.domain.local/images/vCenter_Event_Broker_Appliance_v0.4.0.ova
          version: ''
          filepath: /blueprints/vmw-veba/blueprint.yaml
